Implemented T1-Number Conversion Game
vikrampg1710-tmm/Training pull request #1
Opened 2023-10-04 12:47 UTC by vikrampg1710-tmm

2023-10-10 04:26 UTC, sdinesh-90 requested changes

2023-10-10 04:26 UTC, sdinesh-90 commented on Assignments/Program.cs
> +      Console.WriteLine (output, Console.ForegroundColor = Yellow);
This is incorrect.

2023-10-10 04:26 UTC, sdinesh-90 commented on Assignments/Program.cs
> +         s = ((a < 10) ? a : $"{(char)(87 + a)}") + s;
string concatenation is expensive.

2023-10-10 04:26 UTC, sdinesh-90 commented on Assignments/Program.cs
> +         s = ((a < 10) ? a : $"{(char)(87 + a)}") + s;
Add comments as to what is 87 and why it is used.

2023-10-10 04:26 UTC, sdinesh-90 commented on Assignments/Program.cs
> +         s = ((a < 10) ? a : $"{(char)(87 + a)}") + s;
```suggestion
         s = (a < 10 ? a : $"{(char)(87 + a)}") + s;

```

2023-10-10 04:26 UTC, sdinesh-90 commented on Assignments/Program.cs
> +using System.Linq;
This can be removed.

2023-10-10 15:16 UTC, vikrampg1710-tmm commented
@sdinesh-90 All your suggestions in fecbfa8 have been implemented in the recent commit 215d217.
Please check.

2023-10-10 15:37 UTC, sdinesh-90 requested changes

2023-10-10 15:37 UTC, sdinesh-90 commented on Assignments/Program.cs
> +      }
Single statement don't need { }
```suggestion
      if (int.TryParse (Console.ReadLine (), out int num))
         PrintResult (num);

```

2023-10-10 15:37 UTC, sdinesh-90 commented on Assignments/Program.cs
> +      return new string (Enumerable.Reverse(hex).ToArray());
Formatting
```suggestion
      return new string (Enumerable.Reverse (hex).ToArray ());

```

2023-10-10 15:37 UTC, sdinesh-90 commented on Assignments/Program.cs
> +         if (a < 10) hex.Add (Convert.ToChar ($"{a}"));
Convert.ToChar accepts int also.
```suggestion
         if (a < 10) hex.Add (Convert.ToChar (a));

```

2023-10-10 15:37 UTC, sdinesh-90 commented on Assignments/Program.cs
> +   public static void WriteInYellow (string output) {
WriteInYellow need not be public.

2023-10-10 15:37 UTC, sdinesh-90 commented on Assignments/Program.cs
> +      Console.Write ("\nTry Yourself! Enter input number: ");
```suggestion
      Console.Write ("\nTry yourself! Enter input number: ");

```

2023-10-10 15:37 UTC, sdinesh-90 commented on Assignments/Program.cs
> +         Console.WriteLine ($"\n{i + 1}) {item}");
Try to use Console.WriteLine instead of \n as in Windows next line is \r\n and in Linux it is \n

2023-10-10 17:42 UTC, vikrampg1710-tmm commented on Assignments/Program.cs
> +         Console.WriteLine ($"\n{i + 1}) {item}");
So, if we run this code on the PC with Linux OS, will this cause an error?

2023-10-10 17:45 UTC, vikrampg1710-tmm commented
@sdinesh-90 All your above suggestions have been implemented in the next commit 25dbed1. Please check.

2023-10-11 04:15 UTC, sdinesh-90 commented on Assignments/Program.cs
> +         Console.WriteLine ($"\n{i + 1}) {item}");
It will work as expected in Linux. But in windows if someone assumed that new line will be \r\n and proceed with the assumption it will be wrong.

2023-10-11 04:16 UTC, sdinesh-90 approved these changes

2023-10-11 04:16 UTC, closed without merging