T22 - Swap Indices
vikrampg1710-tmm/Training pull request #22
Opened 2023-11-20 05:03 UTC by vikrampg1710-tmm

T22:
Display random series of numbers to the user and ask them to provide two index values which need to be swapped and display the swapped result to the user. For example, 4 8 7 5 6 9 enter the index to be swapped: 2 3 outputs to be: 4 8 5 7 6 9.

2023-11-27 13:08 UTC, JessDarres requested changes

2023-11-27 13:08 UTC, JessDarres commented on Assignments/Program.cs
> +namespace Spark;
Why you use this?

2023-11-27 13:08 UTC, JessDarres commented on Assignments/Program.cs
> +      PerformIndexSwap ();
Get the inputs and checks are in main method after that you call PerformIndexSwap method.

2023-11-27 13:08 UTC, JessDarres commented on Assignments/Program.cs
> +      static void DisplayInBox (List<int> list, int ind1, int ind2) {
NIce display.

2023-11-27 13:44 UTC, vikrampg1710-tmm commented on Assignments/Program.cs
> +namespace Spark;
Just to indicate this is Spark series task.

2023-11-28 04:54 UTC, JessDarres approved these changes

2023-11-28 04:54 UTC, closed without merging