A15 - Priority Queue
vikrampg1710-tmm/Training pull request #34
Opened 2023-12-15 07:47 UTC by vikrampg1710-tmm

2024-01-05 07:27 UTC, ravin-imm requested changes

2024-01-05 07:27 UTC, ravin-imm commented on Assignments/Program.cs
> +      readonly List<T> queue = new ();
Naming convention not followed.

2024-01-05 07:27 UTC, ravin-imm commented on Assignments/Program.cs
> +         void ShiftDown (int parentIndex) {
The method names should be **SiftDown** and **SiftUp**.

2024-01-05 07:27 UTC, ravin-imm commented on Assignments/Program.cs
> +      /// <exception cref="Exception"></exception>
Format the comments

2024-01-05 07:27 UTC, ravin-imm commented on Assignments/Program.cs
> +            int child1_Index = parentIndex * 2 + 1;
Try to use short words for variable names.

2024-01-08 15:03 UTC, vikrampg1710-tmm commented on Assignments/Program.cs
> +      /// <exception cref="Exception"></exception>
Can you please specify the error?

2024-01-08 15:05 UTC, vikrampg1710-tmm commented on Assignments/Program.cs
> +      readonly List<T> queue = new ();
The field name should have the prefix 'm'.  I will modify it.

2024-01-09 04:04 UTC, ravin-imm commented on Assignments/Program.cs
> +      /// <exception cref="Exception"></exception>
@vikrampg1710-tmm: The start and the end tags should not be in separate lines. The above text can be:
```
      /// <summary>Removes and returns the minimal element from the PriorityQueue<typeparamref name="T"/> - that is, the element with the lowest priority value.</summary>
      /// <returns>Returns the element with the lowest priority value from the queue</returns>
      /// <exception cref="Exception"></exception>
```

2024-01-09 09:37 UTC, ravin-imm approved these changes

2024-01-09 09:37 UTC, closed without merging